import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import toast, { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "Te-Hrms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-lexend antialiased `}>
        <ThemeProvider>
          <Toaster
            toastOptions={{
              position: 'top-center',
              
            }}
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
